app = "rok-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
DATABASE_URL="file:/var/rok-data/dev.db"

[mounts]
source="rok_bot"
destination="/var/rok-data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
